#!/bin/bash
# Run as root after MinIO is up and /etc/minio.env has real root credentials.
# Creates the app bucket and a scoped user. Root stays in /etc/minio.env only.
#   sudo bash deploy/provision-minio-app.sh
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root: sudo bash deploy/provision-minio-app.sh"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MC="${MC_BIN:-/usr/local/bin/mc}"
ENV_FILE="/etc/minio.env"
APP_ENV="/etc/minio-app.env"
BUCKET="${MINIO_APP_BUCKET:-portfolio-uploads}"
APP_USER="${MINIO_APP_USER:-portfolio-app}"
POLICY_NAME="portfolio-app"
ALIAS="localportfolio"
POLICY_RENDER=""

# urlencode encodes a string for use in a URL and writes the result to standard output.
urlencode() {
  local LC_ALL=C
  local i c
  for ((i = 0; i < ${#1}; i++)); do
    c="${1:i:1}"
    case "$c" in
      [a-zA-Z0-9.~_-]) printf '%s' "$c" ;;
      *) printf '%%%02X' "'$c" ;;
    esac
  done
}

# cleanup removes temporary MinIO client environment variables and the rendered policy file.
cleanup() {
  unset "MC_HOST_${ALIAS}" || true
  unset MC_INSECURE || true
  if [ -n "$POLICY_RENDER" ]; then
    rm -f "$POLICY_RENDER"
  fi
}
trap cleanup EXIT

if [ ! -x "$MC" ]; then
  echo "Missing $MC. Run deploy/bootstrap-minio.sh first." >&2
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  echo "Missing $ENV_FILE." >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
# shellcheck source=/dev/null
. "$ENV_FILE"
set +a

if [ -z "${MINIO_ROOT_USER:-}" ] || [ -z "${MINIO_ROOT_PASSWORD:-}" ] \
  || [ "$MINIO_ROOT_USER" = "change-me" ] || [ "$MINIO_ROOT_PASSWORD" = "change-me-at-least-8-chars" ]; then
  echo "Set real MINIO_ROOT_USER and MINIO_ROOT_PASSWORD in $ENV_FILE first." >&2
  exit 1
fi

if [ ! -f "$APP_ENV" ]; then
  APP_PASSWORD="$(openssl rand -base64 24 | tr -d '\n')"
  umask 077
  cat > "$APP_ENV" <<EOF
# Generated by provision-minio-app.sh. Do not commit. Use these in portfolio env.
MINIO_APP_USER=${APP_USER}
MINIO_APP_PASSWORD=${APP_PASSWORD}
MINIO_APP_BUCKET=${BUCKET}
EOF
  chmod 600 "$APP_ENV"
  echo "Wrote scoped credentials to $APP_ENV"
else
  # shellcheck disable=SC1090
  set -a
  # shellcheck source=/dev/null
  . "$APP_ENV"
  set +a
  APP_USER="${MINIO_APP_USER:-$APP_USER}"
  APP_PASSWORD="${MINIO_APP_PASSWORD:-}"
  BUCKET="${MINIO_APP_BUCKET:-$BUCKET}"
  if [ -z "$APP_PASSWORD" ]; then
    echo "$APP_ENV has no MINIO_APP_PASSWORD." >&2
    exit 1
  fi
fi

if [[ ! "$BUCKET" =~ ^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$ ]]; then
  echo "MINIO_APP_BUCKET must be a valid S3 bucket name." >&2
  exit 1
fi

POLICY_RENDER="$(mktemp)"
sed "s/__BUCKET__/${BUCKET}/g" "$SCRIPT_DIR/minio-app-policy.json" > "$POLICY_RENDER"

encoded_user="$(urlencode "$MINIO_ROOT_USER")"
encoded_pass="$(urlencode "$MINIO_ROOT_PASSWORD")"
export MC_INSECURE=1
export "MC_HOST_${ALIAS}=https://${encoded_user}:${encoded_pass}@127.0.0.1:9000"

"$MC" mb --ignore-existing "${ALIAS}/${BUCKET}"
if ! "$MC" admin user info "$ALIAS" "$APP_USER" >/dev/null 2>&1; then
  "$MC" admin user add "$ALIAS" "$APP_USER" "$APP_PASSWORD"
fi
"$MC" admin policy remove "$ALIAS" "$POLICY_NAME" >/dev/null 2>&1 || true
"$MC" admin policy create "$ALIAS" "$POLICY_NAME" "$POLICY_RENDER"
"$MC" admin policy attach "$ALIAS" "$POLICY_NAME" --user "$APP_USER" >/dev/null

echo
echo "Bucket ${BUCKET} and user ${APP_USER} are ready."
echo "Set portfolio to that user from $APP_ENV — not MINIO_ROOT_USER / MINIO_ROOT_PASSWORD."
echo "PORTFOLIO_STORAGE_S3_ACCESS_KEY=${APP_USER}"
echo "PORTFOLIO_STORAGE_S3_BUCKET=${BUCKET}"
echo "Set PORTFOLIO_STORAGE_S3_ENDPOINT to https://127.0.0.1:9000"
echo "Set PORTFOLIO_STORAGE_S3_TRUST_CERT to /etc/minio/certs/public.crt for this self-signed cert."
