#!/bin/bash
# Run as root after MinIO is up and /etc/minio.env has real root credentials.
# Creates the app bucket and a scoped user. Root stays in /etc/minio.env only.
#   sudo bash deploy/provision-minio-app.sh
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root: sudo bash deploy/provision-minio-app.sh"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MC="${MC_BIN:-/usr/local/bin/mc}"
ENV_FILE="/etc/minio.env"
APP_ENV="/etc/minio-app.env"
BUCKET="${MINIO_APP_BUCKET:-portfolio-uploads}"
APP_USER="${MINIO_APP_USER:-portfolio-app}"
POLICY_NAME="portfolio-app"
ALIAS="localportfolio"

if [ ! -x "$MC" ]; then
  echo "Missing $MC. Run deploy/bootstrap-minio.sh first." >&2
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  echo "Missing $ENV_FILE." >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
# shellcheck source=/dev/null
. "$ENV_FILE"
set +a

if [ -z "${MINIO_ROOT_USER:-}" ] || [ -z "${MINIO_ROOT_PASSWORD:-}" ] \
  || [ "$MINIO_ROOT_USER" = "change-me" ] || [ "$MINIO_ROOT_PASSWORD" = "change-me-at-least-8-chars" ]; then
  echo "Set real MINIO_ROOT_USER and MINIO_ROOT_PASSWORD in $ENV_FILE first." >&2
  exit 1
fi

if [ ! -f "$APP_ENV" ]; then
  APP_PASSWORD="$(openssl rand -base64 24 | tr -d '\n')"
  umask 077
  cat > "$APP_ENV" <<EOF
# Generated by provision-minio-app.sh. Do not commit. Use these in portfolio env.
MINIO_APP_USER=${APP_USER}
MINIO_APP_PASSWORD=${APP_PASSWORD}
MINIO_APP_BUCKET=${BUCKET}
EOF
  chmod 600 "$APP_ENV"
  echo "Wrote scoped credentials to $APP_ENV"
else
  # shellcheck disable=SC1090
  set -a
  # shellcheck source=/dev/null
  . "$APP_ENV"
  set +a
  APP_USER="${MINIO_APP_USER:-$APP_USER}"
  APP_PASSWORD="${MINIO_APP_PASSWORD:-}"
  BUCKET="${MINIO_APP_BUCKET:-$BUCKET}"
  if [ -z "$APP_PASSWORD" ]; then
    echo "$APP_ENV has no MINIO_APP_PASSWORD." >&2
    exit 1
  fi
fi

"$MC" alias set "$ALIAS" http://127.0.0.1:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" >/dev/null
"$MC" mb --ignore-existing "${ALIAS}/${BUCKET}"
if ! "$MC" admin user info "$ALIAS" "$APP_USER" >/dev/null 2>&1; then
  "$MC" admin user add "$ALIAS" "$APP_USER" "$APP_PASSWORD"
fi
"$MC" admin policy create "$ALIAS" "$POLICY_NAME" "$SCRIPT_DIR/minio-app-policy.json" >/dev/null 2>&1 || true
"$MC" admin policy attach "$ALIAS" "$POLICY_NAME" --user "$APP_USER" >/dev/null
"$MC" alias remove "$ALIAS" >/dev/null

echo
echo "Bucket ${BUCKET} and user ${APP_USER} are ready."
echo "Set portfolio to that user from $APP_ENV — not MINIO_ROOT_USER / MINIO_ROOT_PASSWORD."
echo "PORTFOLIO_STORAGE_S3_ACCESS_KEY=${APP_USER}"
echo "PORTFOLIO_STORAGE_S3_BUCKET=${BUCKET}"
echo "PORTFOLIO_STORAGE_S3_ENDPOINT=http://127.0.0.1:9000"
